spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml  #指定mapper配置文件位置
  type-aliases-package: com.coderlucifar.transaction.entity              #指定起别名所在包


